In [2]:
import yfinance as yf
dat = yf.Ticker("MSFT")

In [3]:
dat.history(start="2020-01-01", end="2020-12-31")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,151.566834,153.428246,151.137280,153.323242,22622100,0.0,0.0
2020-01-03 00:00:00-05:00,151.127718,152.683659,150.879520,151.414078,21116200,0.0,0.0
2020-01-06 00:00:00-05:00,149.944085,151.872323,149.399972,151.805496,20813700,0.0,0.0
2020-01-07 00:00:00-05:00,152.082316,152.416407,150.173173,150.421356,21634100,0.0,0.0
2020-01-08 00:00:00-05:00,151.710031,153.495089,150.774555,152.817337,27746500,0.0,0.0
...,...,...,...,...,...,...,...
2020-12-23 00:00:00-05:00,215.230633,215.664738,213.002215,213.214447,18699600,0.0,0.0
2020-12-24 00:00:00-05:00,213.600270,215.712929,213.388038,214.883301,10550600,0.0,0.0
2020-12-28 00:00:00-05:00,216.523276,218.047478,215.143785,217.015274,17933500,0.0,0.0
2020-12-29 00:00:00-05:00,218.317577,219.156847,215.683994,216.233856,17403200,0.0,0.0
2020-12-30 00:00:00-05:00,217.275704,217.661587,213.648499,213.851074,20272300,0.0,0.0

In [6]:
yf.download(['MSFT', 'AAPL', 'GOOG'], start='2020-01-01', end='2024-12-31')

[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AAPL        GOOG        MSFT        AAPL        GOOG
Date
2020-01-02   72.716064   68.046204  153.323273   72.776591   68.084520
2020-01-03   72.009132   67.712280  151.414124   72.771760   68.301492
2020-01-06   72.582909   69.381874  151.805496   72.621646   69.495829
2020-01-07   72.241554   69.338585  150.421341   72.849231   69.818809
2020-01-08   73.403656   69.884995  152.817337   73.706287   70.246282
...                ...         ...         ...         ...         ...
2024-12-23  254.989655  195.766968  434.379028  255.369227  196.266399
2024-12-24  257.916443  197.345184  438.450836  257.926411  197.445061
2024-12-26  258.735504  196.875717  437.233276  259.814335  197.934509
2024-12-27  255.309296  193.819183  429.668457  258.415896  196.576052
2024-12-30  251.923019  192.470734  423.979858  253.221595  193.559490

Price                          Low                                Open  \
Ticker            MSFT        AAPL        GOOG        MSFT        AAPL
Date
2020-01-02  153.428276   71.466805   66.761289  151.137310   71.721011
2020-01-03  152.683705   71.783977   66.960045  150.879566   71.941343
2020-01-06  151.872323   70.876075   67.181792  149.399972   71.127866
2020-01-07  152.416391   72.021238   69.191280  150.173158   72.592601
2020-01-08  153.495089   71.943766   69.214168  150.774555   71.943766
...                ...         ...         ...         ...         ...
2024-12-23  436.774220  253.171646  191.411929  431.963858  254.490204
2024-12-24  438.720315  255.009620  194.975874  433.321138  255.209412
2024-12-26  440.057630  257.347047  195.647106  435.756258  257.906429
2024-12-27  434.349074  252.782075  191.753543  425.496829  257.546826
2024-12-30  426.694417  250.474615  190.143383  421.055729  251.952985

Price                                  Volume
Ticker            GOOG        MSFT       AAPL      GOOG      MSFT
Date
2020-01-02   66.761289  151.566865  135480400  28132000  22622100
2020-01-03   67.075298  151.127764  146322800  23728000  21116200
2020-01-06   67.181792  149.944085  118387200  34646000  20813700
2020-01-07   69.567504  152.082300  108872000  30054000  21634100
2020-01-08   69.275872  151.710031  132079200  30560000  27746500
...                ...         ...        ...       ...       ...
2024-12-23  193.809192  435.866037   40858800  15235900  19152500
2024-12-24  195.946768  433.780209   23234700   6809800   7164500
2024-12-26  196.516126  438.201337   27237100   7907900   8194200
2024-12-27  196.246426  433.730320   42355300  14693000  18117700
2024-12-30  190.647813  425.207408   35557500  12209500  13158700

[1257 rows x 15 columns]

In [7]:
# Download data
tickers = ['MSFT', 'AAPL', 'GOOG']
df = yf.download(tickers, start='2020-01-01', end='2024-12-31')

# Separate DataFrames for each ticker
dataframes = {ticker: df.xs(ticker, axis=1, level=1) for ticker in tickers}

[*********************100%***********************]  3 of 3 completed

In [10]:
dataframes['MSFT']

Price            Close        High         Low        Open    Volume
Date
2020-01-02  153.323273  153.428276  151.137310  151.566865  22622100
2020-01-03  151.414124  152.683705  150.879566  151.127764  21116200
2020-01-06  151.805496  151.872323  149.399972  149.944085  20813700
2020-01-07  150.421341  152.416391  150.173158  152.082300  21634100
2020-01-08  152.817337  153.495089  150.774555  151.710031  27746500
...                ...         ...         ...         ...       ...
2024-12-23  434.379028  436.774220  431.963858  435.866037  19152500
2024-12-24  438.450836  438.720315  433.321138  433.780209   7164500
2024-12-26  437.233276  440.057630  435.756258  438.201337   8194200
2024-12-27  429.668457  434.349074  425.496829  433.730320  18117700
2024-12-30  423.979858  426.694417  421.055729  425.207408  13158700

[1257 rows x 5 columns]

In [4]:
import yfinance as yf

# Download data
tickers = ['AA', 'HOV']
df = yf.download(tickers, start='2020-01-01', end='2024-12-31')
output_directory = 'Datasets/New OHLC data'

# Separate DataFrames for each ticker and remove multi-level header
for ticker in tickers:
    single_df = df.xs(ticker, axis=1, level=1)
    single_df.columns = ['Close', 'High', 'Low', 'Open', 'Volume']  # Rename columns
    # single_df.to_csv(f"{output_directory}/{ticker}.csv")  # Save to CSV
    
single_df

[*********************100%***********************]  2 of 2 completed

                 Close        High         Low        Open  Volume
Date
2020-01-02   22.530001   23.280001   20.850000   21.080000  302400
2020-01-03   20.940001   22.280001   20.610001   21.650000  211300
2020-01-06   20.790001   21.459999   20.270000   20.530001  194500
2020-01-07   20.959999   21.309999   20.520000   20.780001  104600
2020-01-08   20.840000   22.400000   20.650000   20.959999  160700
...                ...         ...         ...         ...     ...
2024-12-23  135.399994  135.910004  131.440002  134.259995   70300
2024-12-24  136.320007  136.949997  134.009995  134.809998   26300
2024-12-26  134.529999  136.610001  134.100006  134.110001   46100
2024-12-27  133.270004  135.839996  131.649994  133.789993   66700
2024-12-30  133.949997  133.979996  127.830002  133.429993   99200

[1257 rows x 5 columns]